import {Injectable} from '@angular/core';
import {Http} from '@angular/http';
import {Observable} from 'rxjs/Rx';
import {Subject} from 'rxjs/Rx';
import {BehaviorSubject} from 'rxjs/Rx';
import {ShareService} from './share.service'
import 'rxjs/add/observable/of'; //proper way to import the 'of' operator
import 'rxjs/add/operator/share';
import 'rxjs/add/operator/map';

@Injectable()
export class BackEndService {

    public websocketMessages : Subject<any> = new BehaviorSubject<any>({"type" : "NOMESSAGE"});
    public websocketConnected : Subject<string> = new BehaviorSubject<string>(null);
    websocket : any;
    interval: any;
    messageQue: string[];
    receivedConfirmed: boolean;
    connected : boolean;
    //initiates backend
    constructor(private http: Http, private shareService:ShareService){
        console.log("Initiated backend!");
        this.receivedConfirmed = false;
        this.messageQue = [];
        this.connected = false;
        this.websocketMessages.subscribe((messageRec) => {
             if(messageRec !== null){
                console.log("Message received:");
                console.log(messageRec);
                if(messageRec.type == "irc_data"){
                    if(messageRec.connected){
                        if(!this.connected){                            
                            this.shareService.showMessage("succes", "Connected!");
                            this.shareService.hideLoader();
                            this.connected = true;
                        }
                    } else {
                        this.sendMessage({"action": "connect_irc", "extra" : {"address" : "irc.rizon.net", "username" : "", "channels" : "#nibl"}});
                    }
                    this.shareService.isLocal = messageRec.local;
                }

             }            
        })
    }

    //connects to the backend
    async tryConnecting(address : string){
        
        this.shareService.showLoaderMessage("Waiting for connection to backend!");
        this.websocket = new WebSocket("ws://" + address + ":600");
            
        this.websocket.onopen = (evt : any) =>{
            this.websocketConnected.next(evt);
            
            this.shareService.showLoaderMessage("Waiting for connection to IRC!");
            this.sendMessage({"action": "get_irc_data"});
            clearInterval(this.interval);
        };
        this.websocket.onmessage = (evt : any) => {
            try{                        
                this.websocketMessages.next(JSON.parse(evt.data));
            } catch (e){
                console.log(e);
            }
        }
        this.websocket.onclose = (evt : any)=>{
            this.shareService.showMessage("succes", "Lost connection with backend! Refresh for retry!");   
            if(!this.shareService.isLocal){
                this.shareService.hideLoader();
           
                this.shareService.showModal("Wups!", 
                "I unfortunately lost connection with my backend, just like humans, without my back, I am nothing. You could try reloading. Please check if the backend has crashed or not. If something unexpected happend, you can notify the developer. Please provide the log file generated by the backend!", 
                "frown", 
                `
                    <a onclick="location.href=location.href" class="ui green basic cancel inverted button">
                        <i class="refresh icon"></i>
                        Close.
                    </a>
                    <a href="https://github.com/EldinZenderink/LittleWeeb/issues" class="ui red ok basic inverted button">
                    <i class="announcement icon"></i>
                    Notify the developer!
                    </a>
                ` );                
            }
           
        }
    }

    //sends a message to the backend
    sendMessage(message: any) {
        console.log("pusing message " + message + " to the que");
        
        this.receivedConfirmed = false;
        this.messageQue.push(JSON.stringify(message));
        try {
        

        setInterval(() => {
            try {
                if (this.messageQue.length > 0) {
                    this.websocket.send(this.messageQue[0]);

                    this.messageQue.splice(0, 1);
                    this.receivedConfirmed = false;
                }

            } catch (Ex) {
                console.log("Cannot send message, websocket hasn't been opened yet: ");
                console.log(Ex);
            }

        }, 250);
        }catch(e){
            console.log(e);
        }
    }

    
    
}


